name: Build N64 ROM

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          uname -a
          docker --version

      - name: Pull libdragon toolchain image
        run: docker pull anacierdem/libdragon:latest

        - name: Sanity check files
        run: |
          ls -la
          test -f main.c || { echo "ERROR: main.c missing at repo root"; exit 1; }
          test -f Makefile || { echo "ERROR: Makefile missing"; exit 1; }
        

      - name: Build inside libdragon container
        run: |
          mkdir -p build romfs
          [ -f romfs/version.txt ] || echo v1 > romfs/version.txt
          docker run --rm \
            -v "$PWD:/src" \
            anacierdem/libdragon:latest \
            bash -lc 'cd /src && make clean all'

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms_alpha
          path: |
            *.z64
            *.elf
            build/**
